# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyInsomnia(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InsomniaBinary:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyInsomnia", llm_response=llm_response, mode="request")
        return typing.cast(types.InsomniaBinary, __result__)

    def ExtractInsomniaEvidence(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InsomniaEvidenceExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInsomniaEvidence", llm_response=llm_response, mode="request")
        return typing.cast(types.InsomniaEvidenceExtraction, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyInsomnia(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InsomniaBinary:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyInsomnia", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InsomniaBinary, __result__)

    def ExtractInsomniaEvidence(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InsomniaEvidenceExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInsomniaEvidence", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InsomniaEvidenceExtraction, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, __result__)

    