# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class InsomniaBinary(BaseModel):
    insomnia: typing.Optional[typing.Union[typing_extensions.Literal['yes'], typing_extensions.Literal['no']]] = Field(default=None, description='Whether the patient has insomnia per Rule A, Rule B, or Rule C in the task instructions')

class InsomniaEvidenceExtraction(BaseModel):
    definition_1: typing.Optional["RuleEvidence"] = Field(default=None, description='Definition 1: Difficulty Sleeping')
    definition_2: typing.Optional["RuleEvidence"] = Field(default=None, description='Definition 2: Daytime Impairment')
    rule_b: typing.Optional["RuleEvidence"] = Field(default=None, description='Rule B: primary insomnia medications')
    rule_c: typing.Optional["RuleEvidence"] = Field(default=None, description='Rule C: secondary insomnia medications with Definition 1 or 2 symptoms')

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class RuleEvidence(BaseModel):
    label: typing.Optional[typing.Union[typing_extensions.Literal['yes'], typing_extensions.Literal['no']]] = None
    evidence_quotes: typing.List[str] = Field(description='Verbatim substrings copied from the note that support the label; use empty list when label is no')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
