# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (4)
# #########################################################################

class InsomniaBinary(BaseModel):
    insomnia: typing.Union[typing_extensions.Literal['yes'], typing_extensions.Literal['no']] = Field(description='Whether the patient has insomnia per Rule A, Rule B, or Rule C in the task instructions')

class InsomniaEvidenceExtraction(BaseModel):
    definition_1: "RuleEvidence" = Field(description='Definition 1: Difficulty Sleeping')
    definition_2: "RuleEvidence" = Field(description='Definition 2: Daytime Impairment')
    rule_b: "RuleEvidence" = Field(description='Rule B: primary insomnia medications')
    rule_c: "RuleEvidence" = Field(description='Rule C: secondary insomnia medications with Definition 1 or 2 symptoms')

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class RuleEvidence(BaseModel):
    label: typing.Union[typing_extensions.Literal['yes'], typing_extensions.Literal['no']]
    evidence_quotes: typing.List[str] = Field(description='Verbatim substrings copied from the note that support the label; use empty list when label is no')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
