# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (4)
# #########################################################################

class ClinicalNoteExtraction(BaseModel):
    sleep_difficulty: typing.List["SleepDifficulty"] = Field(description='All Definition 1 (difficulty sleeping) criteria found; empty array if none')
    daytime_impairment: typing.List["DaytimeImpairment"] = Field(description='All Definition 2 (daytime impairment) criteria found; empty array if none')
    medications: typing.List["MedicationMention"] = Field(description='All primary or secondary insomnia medications mentioned in the note; empty array if none')
    reasoning: str = Field(description='One or two sentences describing any exclusions applied, or \'No exclusions applied\'')

class DaytimeImpairment(BaseModel):
    criterion: typing.Union[typing_extensions.Literal['fatigue_malaise'], typing_extensions.Literal['impaired_attention'], typing_extensions.Literal['impaired_performance'], typing_extensions.Literal['mood_disturbance'], typing_extensions.Literal['daytime_sleepiness'], typing_extensions.Literal['behavioral_problems'], typing_extensions.Literal['decreased_motivation'], typing_extensions.Literal['error_proneness'], typing_extensions.Literal['sleep_dissatisfaction'], typing_extensions.Literal['explicit_insomnia']] = Field(description='Which Definition 2 criterion this evidence supports')
    citation: str = Field(description='Verbatim minimal substring copied character-for-character from the note')
    match_regex: str = Field(description='A regex string that uniquely locates the citation in the note')

class MedicationMention(BaseModel):
    name: str = Field(description='Medication name exactly as it appears in the note (may include misspellings or brand variants)')
    normalized_name: str = Field(description='Canonical medication name, e.g. \'Zolpidem\' even if note says \'zolpdem\'')
    med_type: typing.Union[typing_extensions.Literal['primary'], typing_extensions.Literal['secondary']] = Field(description='\'primary\' = Rule B medication list; \'secondary\' = Rule C medication list')
    citation: str = Field(description='Verbatim substring from the note showing the medication mention in context')

class SleepDifficulty(BaseModel):
    criterion: typing.Union[typing_extensions.Literal['trouble_initiating'], typing_extensions.Literal['trouble_maintaining'], typing_extensions.Literal['early_awakening'], typing_extensions.Literal['explicit_insomnia']] = Field(description='Which Definition 1 criterion this evidence supports')
    citation: str = Field(description='Verbatim minimal substring copied character-for-character from the note')
    match_regex: str = Field(description='A regex string that uniquely locates the citation in the note')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
