# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.InsomniaBinary": types.InsomniaBinary,
    "stream_types.InsomniaBinary": stream_types.InsomniaBinary,

    "types.InsomniaEvidenceExtraction": types.InsomniaEvidenceExtraction,
    "stream_types.InsomniaEvidenceExtraction": stream_types.InsomniaEvidenceExtraction,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.RuleEvidence": types.RuleEvidence,
    "stream_types.RuleEvidence": stream_types.RuleEvidence,


}