# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClinicalNoteExtraction": types.ClinicalNoteExtraction,
    "stream_types.ClinicalNoteExtraction": stream_types.ClinicalNoteExtraction,

    "types.DaytimeImpairment": types.DaytimeImpairment,
    "stream_types.DaytimeImpairment": stream_types.DaytimeImpairment,

    "types.MedicationMention": types.MedicationMention,
    "stream_types.MedicationMention": stream_types.MedicationMention,

    "types.SleepDifficulty": types.SleepDifficulty,
    "stream_types.SleepDifficulty": stream_types.SleepDifficulty,


}